<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="wwwroot\Controllers\AboutController.cs" />
    <Compile Include="wwwroot\Controllers\ContactController.cs" />
    <Compile Include="wwwroot\Controllers\DashboardController.cs" />
    <Compile Include="wwwroot\Controllers\DefaultController.cs" />
    <Compile Include="wwwroot\Controllers\ExperienceController.cs" />
    <Compile Include="wwwroot\Controllers\FeatureController.cs" />
    <Compile Include="wwwroot\Controllers\HomeController.cs" />
    <Compile Include="wwwroot\Controllers\LayoutController.cs" />
    <Compile Include="wwwroot\Controllers\MessageController.cs" />
    <Compile Include="wwwroot\Controllers\PortfolioController.cs" />
    <Compile Include="wwwroot\Controllers\SkillController.cs" />
    <Compile Include="wwwroot\Controllers\SocialMediaController.cs" />
    <Compile Include="wwwroot\Controllers\StatisticController.cs" />
    <Compile Include="wwwroot\Controllers\TestimonialController.cs" />
    <Compile Include="wwwroot\Controllers\ToDoListController.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Include="wwwroot\Ready-Bootstrap-Dashboard-master\.DS_Store" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.TagHelpers" Version="2.1.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="8.0.7" />
  </ItemGroup>

</Project>
